### ISSUE TITLE
Support GraphQL

### ISSUE THREAD

**Issue by kalicki** [spider-gazelle/spider-gazelle#1]
One suggestion is to support GRAPHQL natively (it's the future)
Idea: https://github.com/ziprandom/graphql-crystal

**Comment by stakach** [comment]
We’re building support for https://www.arangodb.com/ at the moment

Looking to be pretty database agnostic but definitely focusing on modern DB tech.

Have you checked out the spider-gazelle model code?

**Comment by kalicki** [comment]
Problem of ArangoDB is the use of memory, still not efficient...
Idea: https://www.prismagraphql.com/ is to use layer of layer like this

**Comment by kalicki** [comment]
I checked the Model, looks pretty clean and organized, seems to be easy to expand to other ideas ;)

**Comment by kalicki** [comment]
Other: https://www.graphile.org/

**Comment by kalicki** [comment]
https://github.com/solisoft/arangocr 
ArangoDB for Crystal

**Comment by solisoft** [comment]
Hey I wrote this shard :) I'm a big fan of arangoDB

**Comment by caspiano** [comment]
I think this is a seperate concern from this web framework.

**Comment by solisoft** [comment]
:(

**Comment by caspiano** [comment]
@solisoft There are a few graphql libraries, such as [this one](https://github.com/graphql-crystal/graphql) and the one you mentioned.

If you’d like to propose an API, I’d be interested in collaborating, keeping in mind this framework is relatively minimal (“full stack” in the documentation is a bit of a misnomer, IMO).
