### ISSUE TITLE
How to handle https SSL_connect issue when deploy?

### ISSUE THREAD

**Issue by zw963** [spider-gazelle/spider-gazelle#13]
Hi, @stakach , this is not a spider-gazelle issue, but, just a discuss of https://github.com/spider-gazelle/spider-gazelle/blob/master/Dockerfile, 

And, i have one SSL_connect issue which happen when i build my tiny [myip app](https://github.com/zw963/myip) use alpine static on arch linux(latest), then deploy it on a older `CentOS Stream release 8`.

When i run it with following command, i get error.

```
[root@192 /]# ./myip -l
ip111.cn：从国内测试：1.1.1.1 中国SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
ip111.cn：从国外测试：2.2.2.2 香港 
ip111.cn：从谷歌测试：2.2.2.2 香港 
SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Timeout!
```

the complete backtrace is this:

```
Unhandled exception in spawn: SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (OpenSSL::SSL::Error)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```

In fact, i ask this question on forum [here](https://forum.crystal-lang.org/t/alpine-static-compiled-binary-failed-with-routinescertificate-verify-failed-openssl-error-when-run-it-on-centos-8/4946), straight-shoota give me some really useful [answer](https://forum.crystal-lang.org/t/alpine-static-compiled-binary-failed-with-routinescertificate-verify-failed-openssl-error-when-run-it-on-centos-8/4946/2?u=zw963), but i still want to know your's solution in practice, i saw code like this, https://github.com/spider-gazelle/spider-gazelle/blob/master/Dockerfile#L100-L101, so, your way is just copy cert file to a place, and set `SSL_CERT_FILE` to there, right?

Thanks.

**Comment by stakach** [comment]
yeah, those lines and the earlier `RUN update-ca-certificates`
