### ISSUE TITLE
Name Spider-Gazelle

### ISSUE THREAD

**Issue by kalicki** [spider-gazelle/spider-gazelle#2]
There is already a project with the same name but for ruby. would not something better be more creative?

https://github.com/cotag/spider-gazelle

**Comment by stakach** [comment]
lol we built that project too and liked the name :)
We're re-building cotag in crystal lang so this spider-gazelle is the evolution of the previous version.

**Comment by kalicki** [comment]
I saw that you are comiiter, but both projects can be confused with the same purpose but with equal names. What sets it apart is the language. IMHO =/
