### ISSUE TITLE
Decrease Latency

### ISSUE THREAD

**Issue by s0kil** [spider-gazelle/spider-gazelle#5]
Looking at these benchmarks: https://github.com/the-benchmarker/web-frameworks
`spider-gazelle` average response time is 6.70 ms for a simple application.

What can be done to decrease the response time?

Maybe using a `radix tree`will result in efficient matching and therefore decrease response time?
Similar to:
- https://github.com/buaazp/fasthttprouter
- https://github.com/c9s/r3
- https://github.com/jeremyevans/roda

**Comment by proyb6** [comment]
Perhaps, you should test on your dedicated setup to get accurate timing when the author have mentioned the benchmark isn’t ready for production.

Even my VPS network tends to fluctuations in milliseconds. We would also need to compare the header size.

**Comment by stakach** [comment]
A typical response time is in [Microseconds](https://en.wikipedia.org/wiki/Microsecond). Only When under heavy load, i.e. 140,000 requests a second does the response time increase.

Look at [Ambers](https://amberframework.org/) response time in the same test:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/368013/46169050-b211e900-c25f-11e8-9efe-d92ba13048e9.png">

We're already using a radix tree for efficient matching too: https://github.com/luislavena/radix
The reason languages like Ruby maintain high response times in the test is they are dropping requests.
