### ISSUE TITLE
spider-gazelle.net website cannot access

### ISSUE THREAD

**Issue by blueway** [spider-gazelle/spider-gazelle#6]
spider-gazelle.net website cannot access , maybe  you should use the github pages, i think the   `spide`  is a sensitive word

**Comment by stakach** [comment]
https://spider-gazelle.net/

Works for me. It's using github pages and being served by cloud-front for speed and SSL.

**Comment by stakach** [comment]
Are you on a corporate network? Possibly behind a proxy?

**Comment by blueway** [comment]
Maybe my country block the domain.

**Comment by stakach** [comment]
China? Weird, I don't think there is anything sensitive on there..
You can view directly on github pages: https://spider-gazelle.github.io/guide/

**Comment by blueway** [comment]
Thanks ,it works
