### ISSUE TITLE
Using environment variable to customize env

### ISSUE THREAD

**Issue by waghanza** [spider-gazelle/spider-gazelle#8]
Hi @stakach,

The actual way to customize environment (change **hostname** or **port** for `example`) is don e by the command line (adding an option)

https://github.com/spider-gazelle/spider-gazelle/blob/8d37f5ecedaf181ad114d72c54f9c8933c542772/Dockerfile#L23

It could be accurate to use `environment variable` for that, this is a kind of standard usage for frameworks (across many language)

What do you think ?

Regards,

**Comment by stakach** [comment]
Yeah I could add environment variable support for those.
Command line options are nice for development.

**Comment by stakach** [comment]
fixed in e24e068cdd9ebebd081eb5ce84881e93b17dfebf

**Comment by waghanza** [comment]
@stakach I see `SG_SERVER_PORT` and `SG_SERVER_HOST` in https://github.com/spider-gazelle/spider-gazelle/commit/e24e068cdd9ebebd081eb5ce84881e93b17dfebf, but what about `-w` in https://github.com/the-benchmarker/web-frameworks/blob/master/crystal/spider-gazelle/Dockerfile#L11 ?

**Comment by stakach** [comment]
Ahh sorry, I've added that too: `SG_PROCESS_COUNT`

**Comment by waghanza** [comment]
Thanks :tada:
